apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: rhdevhub-catalog-component
  title: RH DevHub 
  description: |
    Componente del Portal de Ingeniería de Plataforma de Red Hat 
  links:
    - title: Acceso Portal
      url: https://redhat-developer-hub-rhdevhub.apps.cluster-ss754.ss754.sandbox1459.opentlc.com
    - title: MyApp Issues
      url: https://jira.myapp.com
    - title: Blog
      url: https://myapp.example.com/blog
    - title: Slack
      url: https://myapp.example.slack.com
  annotations:
    backstage.io/kubernetes-label-selector: 'app=rhdevhub'
    # backstage.io/kubernetes-id: 'redhat-developer-hub'
    # backstage.io/kubernetes-namespace: rhdevhub
spec: 
  type: website
  owner: departamento_platform_engineering
  lifecycle: development
  system: rhdevhub-system
  children: [rh-devhub___db]
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: rh-devhub___db
  title: PostgreSQL Database for Red Hat Developer Hub
  description: PostgreSQL is a powerful, open source object-relational database system.
  links:
    - url: https://www.postgresql.org
      title: PostgreSQL website
      icon: web
    - url: https://postgresql.org/docs
      title: PostgreSQL Documentation
      icon: web
  annotations:
    backstage.io/kubernetes-label-selector: 'app=postgres_rhdevhub'
    # backstage.io/kubernetes-id: 'redhat-developer-hub-postgresql'
    # backstage.io/kubernetes-namespace: rhdevhub
spec:
  type: database
  lifecycle: development
  owner: departamento_platform_engineering
  system: rhdevhub-system
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: rhdevhub-system
  title: System Red hat Developer Hub
  annotations:
    # backstage.io/kubernetes-label-selector: 'app=postgres_rhdevhub, app=rhdevhub'
    backstage.io/kubernetes-namespace: rhdevhub
spec:
  owner: departamento_platform_engineering
