apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: petstore
  title: Petstore demo project 
  description: |
    Aplicación demo petstore
  links:
    - title: Acceso petstore
      url: https://app-spring-petclinic-petclinic.apps.cluster-rk7ld.rk7ld.sandbox2009.opentlc.com/
    - title: petstore Issues
      url: https://jira.myapp.com
    - title: petstore Blog
      url: https://myapp.example.com/blog
    - title: Slack
      url: https://myapp.example.slack.com
  annotations:
    backstage.io/kubernetes-id: app-spring-petclinic
    backstage.io/kubernetes-namespace: petclinic
    backstage.io/kubernetes-label-selector: 'app=app-spring-petclinic'
spec: 
  type: website
  owner: departamento_desarrollo_software
  lifecycle: development
  system: petstore
  children: []
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: petstore
  title: PostgreSQL Database petstore
  description: PostgreSQL is a powerful, open source object-relational database system.
  links:
    - url: https://www.postgresql.org
      title: PostgreSQL website
      icon: web
    - url: https://postgresql.org/docs
      title: PostgreSQL Documentation
      icon: web
  annotations:
    backstage.io/kubernetes-id: mysql
    backstage.io/kubernetes-namespace: petclinic
    backstage.io/kubernetes-label-selector: 'app=mysql'
spec:
  type: database
  lifecycle: development
  system: petstore
  owner: departamento_desarrollo_software
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: petstore
  title: Petstore System
  annotations:
    backstage.io/kubernetes-id: app-spring-petclinic
    backstage.io/kubernetes-namespace: petclinic
    backstage.io/kubernetes-label-selector: 'app=mysql, app=app-spring-petclinic' 
spec:
  owner: departamento_desarrollo_software
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: petstore
  title: Petstore Backend API
  description: |
    This is a sample Pet Store Server based on the OpenAPI 3.0 specification.  You can find out more about
    Swagger at [https://swagger.io](https://swagger.io). In the third iteration of the pet store, we've switched to the design first approach!
    You can now help us improve the API whether it's by making changes to the definition itself or to the code.
    That way, with time, we can improve the API in general, and expose some of the new features in OAS3.
  links:
    - title: Petstore
      url: https://app-spring-petclinic-petclinic.apps.cluster-rk7ld.rk7ld.sandbox2009.opentlc.com/
    - title: Petstore API
      url: https://app-spring-petclinic-petclinic.apps.cluster-rk7ld.rk7ld.sandbox2009.opentlc.com/swagger-ui/
spec:
  type: openapi
  system: petstore
  owner: departamento_desarrollo_software
  lifecycle: development
  definition:
    $openapi: https://github.com/OAI/OpenAPI-Specification/blob/main/examples/v3.0/petstore.yaml